### ISSUE TITLE
NameError: uninitialized constant Vagrant::Action::Builtin::NFS

### ISSUE THREAD

**Issue by dglynn** [blueboxgroup/razor-vagrant-lab#9]
Hi,

I keep getting an error when running 'vagrant up razor'. I think its linked to the /lib/lab/vagrant_middleware.rb file
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /path/to/Vagrantfile
Line number: 5
Message: NameError: uninitialized constant Vagrant::Action::Builtin::NFS

If i comment out these 2 modules/classes the razor will build and then fail when it tries to run some chef files that need those settings later on in the build.

Vagrant::Action::Builtin::NFS,
VagrantPlugins::ProviderVirtualBox::Action::ShareFolders,

Vagrant version is 1.8.1

$vagrant plugin list 
vagrant-berkshelf (4.1.0)
vagrant-bindfs (0.4.6)
vagrant-omnibus (1.4.1)

rgds
Darren

**Comment by dglynn** [comment]
I guess this repo is no longer maintained then....?

**Comment by scoop206** [comment]
yes, we are not maintaining the anymore.  Sorry we missed your first query.

-sam
